services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: campimove_backend
    depends_on:
      - postgres
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/campimove_api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=campimove@gmail.com
      - SPRING_MAIL_PASSWORD=yjewagawctdcepyc

      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: campimove_frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_DB=campimove_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-cache
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  redis_data: